const e = location.pathname.split("/").slice(0, -1).join("/"),
    b = [
        e + "/core/gam-scripts/slowroads/_app/immutable/entry/app.e972eff3.js",
        e + "/core/gam-scripts/slowroads/_app/immutable/nodes/0.e1749fc5.js",
        e + "/core/gam-scripts/slowroads/_app/immutable/nodes/1.033497dd.js",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/2.f5ef3045.css",
        e + "/core/gam-scripts/slowroads/_app/immutable/nodes/2.8410b8f1.js",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/auto_on.da4fbe10.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/auto_off.dc550416.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coupe_main_new.53837d9a.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coupe_wheel.a5e44cdf.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coupe_interior.6ee6e82e.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coupe_dash.c2d78df2.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coupe_steering.4443a960.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coupe_map.76d2e800.jpg",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coupe_window.cee5417c.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coach_main.9fa80d57.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coach_interior.10318910.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coach_window.b801ee83.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/bike_main.c972f06f.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/bike_interior.a5fd5b53.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/bike_wheel.15deee9d.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/bike_window.9bc8bd2b.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/coupe_boost.5c7ff2f7.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/brake.fe62943d.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/roll_tarmac_01.946ae363.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/roll_tarmac_int.e8cc8d26.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/roll_gravel.81af40f4.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/roll_gravel_int.c7b362d0.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/hit_01.9e9c259f.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/hit_01_int.c2f91a7b.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/hit_02.69c75a35.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/hit_02_int.44f13e76.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/hit_03.28674fc6.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/hit_03_int.00b2a132.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/skid_tarmac.a73c8b33.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/skid_tarmac_int.98007200.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/skid_wet.b41804bd.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/skid_wet_int.2f3a8990.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/scrape_metal.417cfe49.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/scrape_metal_int.76a3645c.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/suspension.1c4c4b73.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/grass.4bda3c44.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_grasses.aba07908.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_bushes.fde93a5c.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/forest_spring.5805c168.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/gravel_02.8367ed2c.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/sand.43e5b6fc.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_rock.debe0fc3.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/rock_bump.799497d7.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_heather_05.5f56558d.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/road.7b49175b.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_road_single.f107e8b9.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_imposters_0_d.fac9b679.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_imposters_0_n.1d5afe54.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_imposters_1_d.23f6c550.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_imposters_1_n.2a7e8cf6.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_trees_0.f07c6052.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_trees_0_n.8e3ce8fa.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_trees_1_m.a49d7f91.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_trees_1_a.e8f53ceb.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/wall_barrier.ae25acc8.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/wall_concrete.1580ba60.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_wall_barrier_wood.d3a4921f.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/spring_wall_drystone.90ffb8f9.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/ambiance_spring_01.7b64f1e2.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/ambiance_cloudy_01.9c19be76.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/wind_01.95bb0ace.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/bridge.7eaed52d.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/clouds_01.700a3fdb.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/road_single.5bad892b.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/gravel.0ee4475c.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_rock.d8546b99.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_bushes.da0f8901.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/forest_01.5b281e83.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_imposters_0_d.d669095a.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_imposters_0_n.99abbc99.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_imposters_1_d.b55379af.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_trees_0.dd1778e2.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_trees_0_n.011e666e.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_trees_1_m.30de289d.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/summer_trees_1_a.c88ed1f2.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/wall_barrier_wood.b1fb9a80.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/wall_drystone.5c33e841.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/ambiance_summer_low_01.6d623f8c.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_grasses.7c3aa37e.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_bushes.6f035f4d.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/forest_autumn.ce75ab29.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_heather.d890b430.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_road.4523f529.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_road_single.cc46ef90.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_imposters_0_d.4c4b38fd.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_imposters_0_n.d10ccd46.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_imposters_1_d.91faf517.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_trees_0.2fe560b0.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_trees_0_n.a664e3e1.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_trees_1_m.2cd39e32.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/autumn_trees_1_a.2aa926cb.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_grass.2126ead2.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_grasses.fbb53d0d.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_bushes.8e9f3165.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/forest_winter.0710a850.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_rock.26d920c2.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_gravel.03b9e4e9.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_heather.b9aeb76f.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_road.3600c7db.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_road_bridge.43e1a074.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_road_single.9deb67a4.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_road_single_bridge.ff0f85b5.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_imposters_0_d.ce1a9b7d.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_imposters_0_n.8293f6b6.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_imposters_1_d.2882c5c9.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_trees_0.99189e5d.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_trees_0_n.24c5f705.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_trees_1_m.7ee3e863.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_trees_1_a.142fe383.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_wall_barrier.2f3faaf6.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_wall_concrete.edcd548c.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_wall_barrier_wood.058b9fbc.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/winter_wall_drystone.3694f7ac.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/noise_fine.9cdaf478.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/noise_finer.56c77b62.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/sea_waves.63ff8729.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/signs.c90afd62.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/tree_01.9bcc15de.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/tree_02.b1337f12.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/tree_03.cad49780.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/tree_04.e763f7c8.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/tree_05.d68751e5.obj",
        e + "/core/gam-scripts/slowroads WEIGHT/_app/immutable/assets/tree_06.693be0d9.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/tree_07.516fbdda.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/tree_08.b8bd204c.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/noise_fine.a3591251.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/noise_finer.962cd5d7.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/moon_earthrise.83efb4ea.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/road.b7244e6d.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/surface.3f731193.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/subsurface.d2457f82.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/shale.cf612df1.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/rock.406b86d4.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/cliff.98c2faee.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/surface_bump.407d34e6.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/shale_bump.ef432da7.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/rock_bump.6b80e0a0.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/cliff_bump.e1ae5f41.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/mars_barrier.7fc3990d.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/venus_barrier.1da04649.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/rubble_base.d5a2ad78.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/clouds_01.ab586e6c.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/ambiance_offworld.3f009ed2.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/wind_offworld_02.2eeaa401.mp3",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/mars.6e822973.svg",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/moon.82740ed8.svg",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/venus.74f8d050.svg",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/rock.94cc093e.obj",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/noentry.71ff3d6f.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/chunks/index.85bbc95f.js",
        e + "/core/gam-scripts/slowroads/_app/immutable/chunks/index.f66a2b2d.js",
        e + "/core/gam-scripts/slowroads/_app/immutable/chunks/scheduler.6cda8fd7.js",
        e + "/core/gam-scripts/slowroads/_app/immutable/chunks/singletons.9f85c147.js",
        e + "/core/gam-scripts/slowroads/_app/immutable/entry/start.420fd423.js",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/sand_02.2f5ccc75.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/rubble_moon.d0d3b76b.webp",
        e + "/core/gam-scripts/slowroads/_app/immutable/assets/debug_main.9210b9fe.obj"
    ],
    u = [
        e + "/core/gam-scripts/slowroads/5CBE07E9.png",
        e + "/core/gam-scripts/slowroads/5CBE07EA.png",
        e + "/core/gam-scripts/slowroads/alea.min.js",
        e + "/core/gam-scripts/slowroads/apple-touch-icon.png",
        e + "/core/gam-scripts/slowroads/favicon.png",
        e + "/core/gam-scripts/slowroads/favicon.svg",
        e + "/core/gam-scripts/slowroads/favicon_dark.svg",
        e + "/core/gam-scripts/slowroads/favicon_light.svg",
        e + "/core/gam-scripts/slowroads/favicon_old.svg",
        e + "/core/gam-scripts/slowroads/fonts/Sono.ttf",
        e + "/core/gam-scripts/slowroads/fonts/Space.ttf",
        e + "/core/gam-scripts/slowroads/icon.svg",
        e + "/core/gam-scripts/slowroads/icon_coloured.svg",
        e + "/core/gam-scripts/slowroads/icon_coloured_comfy.svg",
        e + "/core/gam-scripts/slowroads/icon_coloured_tight.svg",
        e + "/core/gam-scripts/slowroads/img/bg_summer_01.jpg",
        e + "/core/gam-scripts/slowroads/img/bg_summer_01_b.webp",
        e + "/core/gam-scripts/slowroads/img/bg_summer_02.jpg",
        e + "/core/gam-scripts/slowroads/img/bg_summer_02_b.webp",
        e + "/core/gam-scripts/slowroads/img/bg_summer_03_b.webp",
        e + "/core/gam-scripts/slowroads/img/driftmas_route.svg",
        e + "/core/gam-scripts/slowroads/img/ico_boost.svg",
        e + "/core/gam-scripts/slowroads/img/ico_brake.svg",
        e + "/core/gam-scripts/slowroads/img/ico_gamepad.svg",
        e + "/core/gam-scripts/slowroads/img/ico_kofi.svg",
        e + "/core/gam-scripts/slowroads/img/ico_lock_closed.svg",
        e + "/core/gam-scripts/slowroads/img/ico_lock_open.svg",
        e + "/core/gam-scripts/slowroads/img/ico_onwards.svg",
        e + "/core/gam-scripts/slowroads/img/ico_scene_autumn.svg",
        e + "/core/gam-scripts/slowroads/img/ico_scene_spring.svg",
        e + "/core/gam-scripts/slowroads/img/ico_scene_summer.svg",
        e + "/core/gam-scripts/slowroads/img/ico_scene_winter.svg",
        e + "/core/gam-scripts/slowroads/img/ico_settings.svg",
        e + "/core/gam-scripts/slowroads/img/ico_stats.svg",
        e + "/core/gam-scripts/slowroads/img/ico_time_day.svg",
        e + "/core/gam-scripts/slowroads/img/ico_time_evening.svg",
        e + "/core/gam-scripts/slowroads/img/ico_time_halfsun.svg",
        e + "/core/gam-scripts/slowroads/img/ico_time_morning.svg",
        e + "/core/gam-scripts/slowroads/img/ico_time_night.svg",
        e + "/core/gam-scripts/slowroads/img/ico_uturn.svg",
        e + "/core/gam-scripts/slowroads/img/ico_veh_bike.svg",
        e + "/core/gam-scripts/slowroads/img/ico_veh_coach.svg",
        e + "/core/gam-scripts/slowroads/img/ico_veh_coupe.svg",
        e + "/core/gam-scripts/slowroads/img/ico_volume_off.svg",
        e + "/core/gam-scripts/slowroads/img/ico_volume_on.svg",
        e + "/core/gam-scripts/slowroads/img/ico_warning.svg",
        e + "/core/gam-scripts/slowroads/img/ico_weather_clear.svg",
        e + "/core/gam-scripts/slowroads/img/ico_weather_overcast.svg",
        e + "/core/gam-scripts/slowroads/img/icon_discord.svg",
        e + "/core/gam-scripts/slowroads/img/icon_steam.png",
        e + "/core/gam-scripts/slowroads/img/icon_steam.svg",
        e + "/core/gam-scripts/slowroads/img/icon_steam_white.svg",
        e + "/core/gam-scripts/slowroads/img/logo-stacked.svg",
        e + "/core/gam-scripts/slowroads/img/topo-square-dark.webp",
        e + "/core/gam-scripts/slowroads/img/topo-square-light.webp",
        e + "/core/gam-scripts/slowroads/img/topo_square.png",
        e + "/core/gam-scripts/slowroads/img/topo_square_dark.png",
        e + "/core/gam-scripts/slowroads/img/topo_square_inverted.png",
        e + "/core/gam-scripts/slowroads/manifest.json",
        e + "/core/gam-scripts/slowroads/meta-2.0.0.jpg"
    ],
    l = "1740770437175",
    _ = `cache-${l}`,
    i = [...b, ...u];
self.addEventListener("install", s => {
    async function p() {
        await (await caches.open(_)).addAll(i)
    }
    s.waitUntil(p())
});
self.addEventListener("activate", s => {
    async function p() {
        for (const a of await caches.keys()) a !== _ && await caches.delete(a)
    }
    s.waitUntil(p())
});
self.addEventListener("fetch", s => {
    if (s.request.method !== "GET") return;
    async function p() {
        const a = new URL(s.request.url),
            t = await caches.open(_);
        if (i.includes(a.pathname)) return t.match(a.pathname);
        try {
            const m = await fetch(s.request);
            return m.status === 200 && t.put(s.request, m.clone()), m
        } catch {
            return t.match(s.request)
        }
    }
    s.respondWith(p())
});
