name: Combine Unity Split Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: List build directory (for debugging)
        run: ls -l ./core/gam-scripts/131-car/Build/

      - name: Combine data files
        run: |
          cat ./core/gam-scripts/131-car/Build/WebGL.data.unityweb.*.part > ./core/gam-scripts/131-car/Build/WebGL.data.unityweb || echo "Data files missing!"
          cat ./core/gam-scripts/131-car/Build/WebGL.wasm.code.unityweb.*.part > ./core/gam-scripts/131-car/Build/WebGL.wasm.code.unityweb || echo "WASM code files missing!"

      - name: Commit combined files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./core/gam-scripts/131-car/Build/WebGL.data.unityweb ./core/gam-scripts/131-car/Build/WebGL.wasm.code.unityweb
          git commit -m "Combine split Unity files" || echo "No changes to commit"
          git push
