name: Combine Unity Split Files

on:
  push:
    branches:
      - main  # Change to your branch name if not using 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Combine data files
        run: |
          cat ./core/gam-scripts/131-car/Build/WebGL.data.unityweb.* > ./core/gam-scripts/131-car/Build/WebGL.data.unityweb
          cat ./core/gam-scripts/131-car/Build/WebGL.wasm.code.unityweb.* > ./core/gam-scripts/131-car/Build/WebGL.wasm.code.unityweb
      - name: Commit combined files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./core/gam-scripts/131-car/Build/WebGL.data.unityweb ./core/gam-scripts/131-car/Build/WebGL.wasm.code.unityweb
          git commit -m "Combine split Unity files"
          git push
